### ISSUE TITLE
Mention Documentation

### ISSUE THREAD

**Issue by ericholscher** [ascott1/ethicalweb.org#2]
It seems like you've left out the value of documentation in your set of ethics. It seems that if you value tests and linting, documentation seems like an obvious thing to also value.

**Comment by ascott1** [comment]
Oh yes, that is a very notable omission. Thanks @ericholscher!

**Comment by ascott1** [comment]
Principle #4 now adds:

> Comment and document code

Thanks for the recommendation @ericholscher! I'm adding you as a contributor to the `humans.txt` file, which will also be referenced as part of the contributor list in the books. Please let me know if you would prefer not to be included.

**Comment by ericholscher** [comment]
Sounds great, thanks!
